pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(System.DefaultWorkingDirectory)/.azure-pipeline/YamplParser'
- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    projects: '$(System.DefaultWorkingDirectory)/.azure-pipeline/YamplParser'
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/.azure-pipeline/gitdiff.ps1'
    arguments: '$(Build.SourceVersion)'    
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/.azure-pipeline/ymlparser.ps1'
    arguments: '$(yamlFileName)'
- script: echo "$(customerName)"