pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/.azure-pipeline/gitdiff.ps1'
    arguments: '$(Build.SourceVersion)'    
- task: PowerShell@2
  inputs:
    filePath: 'ymlparser.ps1'
    arguments: '$(yamlFileName)'  
- script: echo "$(customerName)"